CREATE TABLE items(
id NUMBER(4) PRIMARY KEY,
name VARCHAR2(30 CHAR) NOT NULL UNIQUE,
price NUMBER(7) DEFAULT 0 NOT NULL,
registration_date DATE DEFAULT SYSDATE NOT NULL,
update_date DATE DEFAULT SYSDATE NOT NULL,
category_id NUMBER(4),
FOREIGN KEY(category_id) REFERENCES categories(id)
);

CREATE TABLE categories (
  id NUMBER(4) PRIMARY KEY,
  name VARCHAR2(20 CHAR) NOT NULL UNIQUE,
  registration_date DATE DEFAULT SYSDATE NOT NULL,
  update_date DATE DEFAULT SYSDATE NOT NULL
);

